### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by kakurasan**
This PR adds the `RELEASE` file and sets version to `0.1.0`.

This change will trigger automatic release (but not merged yet).

### CODE REVIEW

**Comment by kakurasan** [comment]
The tag `0.0.1` exists but the step "Fetch all history for all tags and branches" in the job didn't show the tag `0.0.1` for some reasons (retried but same result):

```
$ git init
$ git remote add origin https://github.com/lhark/truckersmp-cli
$ git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +93c7960d7242f0010cee09e7eee57a2ad458365b:refs/remotes/origin/master
$ git checkout --progress --force -B master refs/remotes/origin/master
$ git fetch --prune --unshallow
```

Expected output:

```
Fetch all history for all tags and branches
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
Run git fetch --prune --unshallow
  git fetch --prune --unshallow
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
From https://github.com/lhark/truckersmp-cli
 * [new tag]         0.0.1 -> 0.0.1
```

Actual output:

```
Fetch all history for all tags and branches
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
Run git fetch --prune --unshallow
  git fetch --prune --unshallow
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.3/x64
```

The job was successful on [my forked repository](https://github.com/kakurasan/truckersmp-cli/releases/tag/0.1.0). Strange...

**Comment by Lucki** [comment]
Yes, I've also tested in my repository and it worked there too.

**Comment by kakurasan** [comment]
Copied the changelog and assets from my forked repository. I think it will work *next time* because it shows the tag `0.1.0`.

**Comment by Lucki** [comment]
I've tested a few things yesterday and I had created a `0.0.0` tag but the changelog still failed even with two tags in the history.

**Pull request merged**
