### PR TITLE
Update Wine Discord IPC Bridge to 0.0.1

### PR DESCRIPTION
**Pull request by Lucki**
New exe
New hash
Much smaller

### CODE REVIEW

**Comment by Lucki** [comment]
https://github.com/0e4ef622/wine-discord-ipc-bridge/pull/7

**Comment by kakurasan** [comment]
We need to update also the permanent URL when the hash is updated:
```py
    ipcbrpath = "/0e4ef622/wine-discord-ipc-bridge" + \
        "/236860cebb428777a4a376b92d5d3b5cfdf55d7b/winediscordipcbridge.exe"
```

**Comment by kakurasan** [comment]
> `** DEBUG **  Downloading file https://raw.githubusercontent.comhttps://github.com/0e4ef622/wine-discord-ipc-bridge/releases/download/v0.0.1/winediscordipcbridge.exe to /home/username/.local/share/truckersmp-cli/wine-discord-ipc-bridge`

The current `start_wine_discord_ipc_bridge()` connects to `raw.githubusercontent.com` (`URL.raw_github`) and your new URL would not work. If we use their GitHub Release assets, we need to add `github.com` to `class URL` and specify `URL.github` instead of `URL.raw_github` when calling `download_files()`:

```py
# variables.py
class URL:
    # ...
    github = "github.com"
    ipcbrpath = "/0e4ef622/wine-discord-ipc-bridge/releases/download/" + \
        "v0.0.1/winediscordipcbridge.exe"

# utils.py
def start_wine_discord_ipc_bridge(runner, env):
        # ...
        logging.debug("Downloading winediscordipcbridge.exe")
        os.makedirs(Dir.ipcbrdir, exist_ok=True)
        if not download_files(
                URL.github, [(URL.ipcbrpath, File.ipcbridge, File.ipcbridge_md5), ]):
            sys.exit("Failed to download winediscordipcbridge.exe")
```

BTW unfortunately it still won't work because of an issue in `download_files()`. I opened a PR that fixes it: You need to merge #123 first, then rebase against master.

**Review by kakurasan — APPROVED** [review]
Thanks, I've retested and this is now working.

**Pull request merged**
