### PR TITLE
proton.json: Add Proton 5.13 (1420170) and use it as default

### PR DESCRIPTION
**Pull request by kakurasan**
* https://steamdb.info/app/1420170/
* https://github.com/ValveSoftware/Proton/releases/tag/proton-5.13-1b

@Lucki If you would like to release version 0.2.1 for the new Proton, you can open "Release 0.2.1" PR after merging this.

### CODE REVIEW

**Comment by Lucki** [comment]
Not sure about this. 5.13 is still beta and has some huge regressions: https://github.com/ValveSoftware/Proton/issues/4289

**Comment by Lucki** [comment]
I can't approve this. Using 5.13 in opengl mode (our default) crashes my gnome shell. DXVK works though (after I've activated the workaround again?).
Also controller hot-plugging worked to my surprise, not sure what's that known bug is about then…

Also there's a new error in the log when closing the game: `wine: Unhandled page fault on read access to 00007F87F3743B30 at address 0000000140125029 (thread 0108), starting debugger...`

**Comment by kakurasan** [comment]
OK, thanks for the information. Let's wait at least until the known issues are fixed.

**Comment by Lucki** [comment]
> Using 5.13 in opengl mode (our default) crashes my gnome shell.

While in plasma I retested this and it seems working there so this might be somehow related to gnome.

**Review by Lucki — APPROVED** [review]
Did another check and it's starting smooth now.

**Pull request merged**
