### PR TITLE
README.md: Make it easy for users to find dependencies and how to install

### PR DESCRIPTION
**Pull request by kakurasan**
Only reordering. The contents are not changed.

### CODE REVIEW

**Comment by Lucki** [comment]
The order I've chosen was to put the most important part (to the user) to the top, e.g. "How do I install this"?
The recommended install options are through package managers which are keeping track of dependencies by their own.

It's only necessary to know the exact dependencies if you're
* downloading the pre-built binary,
* making a package or
* building by yourself.

That's why I haven't put them to top and that's why I'm against this reordering.

But I admit we could split the dependencies apart and put the runtime dependencies to the download-install-section and the build deps to the building step (where they already are).

---
Almost missed you've also put it before usage, seems fine. How about this ordering:
* Install
  * Download
  * Run deps
* Usage
* Build
  * build deps

**Review by Lucki — APPROVED** [review]
Do you think we should publish 0.2.0 or do you want to include more before that?

**Comment by kakurasan** [comment]
I think the script is ready for the next release.

I'm considering adding "known issues" stuff to `README.md` for #90 and #91, but the issues are already [pinned](https://github.com/lhark/truckersmp-cli/issues).

One more thing is that we're using OpenGL backend (that has #91) by default. But I don't think that D3D11 backend should be used by default for now, because:

* Native `d3dcompiler_47.dll` is still needed for multiplayer
* Wined3d rendering is still broken
* DXVK has issue #90 (workarounds available)

What do you think? (1.Whether to add "known issues" stuff, 2.Default rendering backend)

**Comment by Lucki** [comment]
I don't have an opinion on the known issue stuff. When I want to know if an issue is already reported or discussed I search the issue section directly. (And mostly ignoring the pinned issues in the process)

Without #90 I would say we could easily make d11 for proton default but with it it's a bit… meh. Downloading the dll is already automated.
For wine we should leave it opengl until we can make sure it's by default good in performance, either by a better wined3d or by invoking DXVK ourself (but that would also result in #90 again).

**Comment by kakurasan** [comment]
> Do you think we should publish 0.2.0 or do you want to include more before that?

@Lucki Now ready to release the version. You can open "Release 0.2.0" PR when you want to do it.

**Pull request merged**
